# GitHub Actions Workflow configuration
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/actions/guides/building-and-testing-nodejs

name: Node.js CI

# Note: on key treated as boolean key by YAML
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-454313233
# However, GitHub Actions documentation is consistent in using it unquoted.
on:   # yamllint disable-line rule:truthy
  pull_request:
    branches-ignore:
    - template
  push:
    branches-ignore:
    - template
  schedule:
  # Run once a day (at 8:40 AM UTC) to check for exogenous breakage.
  # TODO: Run when dependencies are updated.  (Like Dependabot, but on
  # in-range updates and without sending a PR.)
  - cron: '40 8 * * *'
  workflow_dispatch: {}

permissions: {}

jobs:
  test-primary:
    name: Lint and Test on Node.js * x64 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - run: exit

  test-secondary:
    # Only test secondary platforms if primary test platform passed
    needs:
    - test-primary
    name: >-
      Test on Node.js ${{ matrix.node }} ${{ matrix.arch }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
        # Uncomment if package needs testing on different architectures
        # - x86
        - x64
        os:
        # Uncomment if package needs testing on macOS:
        # - macos-latest
        - ubuntu-latest
        - windows-latest
        node:
        - '20.19'
        - latest
        exclude:
        # Exclude os/version already run in test-primary
        - arch: x64
          os: ubuntu-latest
          node: latest
    steps:
    - name: Fail on latest windows-latest
      if: matrix.node == 'latest' && matrix.os == 'windows-latest'
      run: exit 1

  # Job to ensure all other jobs in this workflow succeeded.
  # This job is used for required status checks in rulesets, to avoid
  # enumerating all (matrix) jobs and risking breakage on changes.
  # See: https://github.com/orgs/community/discussions/26733
  all-success:
    # ensure this job always runs, to avoid
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#example-not-requiring-successful-dependent-jobs
    if: always()
    needs: [test-primary, test-secondary]
    runs-on: ubuntu-latest
    steps:
    - name: Fail if any previous jobs failed
      if: >-
        contains(needs.*.result, 'failure')
        || contains(needs.*.result, 'cancelled')
        || contains(needs.*.result, 'skipped')
      run: exit 1
